# Generated by Django 3.1.6 on 2021-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30)),
                ('RollNo', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(max_length=254)),
                ('MobileNo', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('Address', models.TextField()),
            ],
        ),
    ]
