# Generated by Django 3.1.6 on 2021-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
