# Generated by Django 3.1.6 on 2021-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0003_auto_20210215_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
