# Generated by Django 3.1.6 on 2021-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0004_auto_20210215_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RollNo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
