# Generated by Django 3.1.6 on 2021-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0005_auto_20210215_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True),
        ),
    ]
